import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      ".next-dev-*/**",
      "node_modules/**",
      "release/**",
      "build-resources/**",
      ".dashboard-lab-dev-session.json",
      // Generated by Next.js and marked "should not be edited"; from 15.5 it
      // carries a triple-slash reference that trips @typescript-eslint.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
