import { pickLocale, type AppLocale } from "@/lib/locale";
import { getCsChannelLabel, getCsToneLabel } from "@/lib/cs-helper/messages";
import type { CsChannel, CsTone } from "@/lib/types";

export function getCsHelperCopy(locale: AppLocale) {
  const labels = pickLocale(locale, {
    ko: {
      eyebrow: "CS Helper",
      heroTitle: "고객 메시지를 프로젝트 문맥에 맞는 답변 초안으로 정리하는 탭",
      heroDescription:
        "프로젝트별 맥락을 읽은 뒤 고객 응답 초안과 내부 분석 메모를 함께 만듭니다. 단순한 답변 복붙이 아니라, 현재 프로젝트 상황을 반영한 응답 옵션을 빠르게 준비하는 용도입니다.",
      cards: [
        {
          label: "고객 응답",
          title: "문의 답변 초안을 먼저 만들기",
          description: "지연 안내, 오류 대응, 환불 문의처럼 반복되는 케이스를 빠르게 초안화합니다.",
        },
        {
          label: "내부 분석",
          title: "공유용 메모와 판단 근거 정리",
          description: "고객에게 바로 보내지 않을 분석 메모를 분리해서 팀 내부 커뮤니케이션에 활용할 수 있습니다.",
        },
        {
          label: "문맥 반영",
          title: "프로젝트별 컨텍스트와 톤 유지",
          description: "선택한 프로젝트의 배경을 반영해 톤, 채널, 응답 수준을 맞춘 초안을 준비합니다.",
        },
      ],
      coreModeTitle: "간단 모드 안내",
      coreModeMessage:
        "처음에는 프로젝트 하나를 고르고 고객 메시지만 입력한 뒤 고객 응답 초안을 먼저 확인하면 됩니다. 내부 분석은 필요할 때만 같이 생성하면 충분합니다.",
      appliedTitle: "반영되었습니다",
      projectRequired: "프로젝트 선택 필요",
      contextReady: "컨텍스트 준비됨",
      contextInfoTitle: "현재 프로젝트 기준 정보",
      workspaceDescription:
        "고객 메시지를 입력하면 응답을 생성하고, 내부 분석은 필요할 때만 함께 생성할 수 있습니다. 히스토리를 선택하면 당시 설정과 메시지가 같이 복원됩니다.",
      quickPresetTitle: "빠른 응답 프리셋",
      quickPresetDescription: "자주 오는 문의는 프리셋으로 초안을 넣고 바로 수정할 수 있습니다.",
      replyReady: "고객 응답 준비됨",
      analysisReady: "내부 분석 준비됨",
      analysisLoading: "내부 분석 생성 중",
      analysisEmpty: "내부 분석 없음",
      replyTab: "고객 응답",
      analysisTab: "내부 분석",
      analysisPanelTitle: "내부 분석",
      analysisPanelLoading: "내부 분석 생성 중...",
      analysisRegenerate: "분석 다시 생성",
      analysisHint: "답변 생성 시 내부 분석을 함께 켜지 않았다면, 필요할 때 여기서 별도로 생성할 수 있습니다.",
      analysisGenerate: "내부 분석 생성",
      feedback: {
        responseCreatedWithAnalysis: "고객 응답과 내부 분석을 생성했습니다.",
        responseCreated: "고객 응답을 생성했습니다.",
        analysisRegenerated: "내부 분석을 다시 생성했습니다.",
        responseRegeneratedWithAnalysis: "설정을 반영해 CS 응답과 내부 분석을 다시 생성했습니다.",
        responseRegenerated: "설정을 반영해 CS 응답을 다시 생성했습니다.",
        historyRestored: "히스토리 기록을 현재 작업 화면으로 복원했습니다.",
      },
      errors: {
        responseFailed: "응답 생성에 실패했습니다.",
        analysisFailed: "분석 생성에 실패했습니다.",
        regenerateFailed: "재생성에 실패했습니다.",
        requestFailed: "요청 처리에 실패했습니다.",
      },
      presets: [
        {
          id: "delay",
          label: "일정 지연 안내",
          customerMessage: "언제 처리되는지 확인 부탁드립니다. 일정이 계속 밀리고 있어 불편합니다.",
          additionalContext: "지연 사유를 투명하게 설명하고 다음 조치 시점을 분명히 안내",
        },
        {
          id: "refund",
          label: "환불/취소 문의",
          customerMessage: "서비스를 더 이상 이용하지 않으려 합니다. 환불이나 취소 절차를 안내해 주세요.",
          additionalContext: "정책을 넘어서 단정하지 말고 확인 가능한 절차 중심으로 답변",
        },
        {
          id: "bug",
          label: "오류 신고 대응",
          customerMessage: "방금 기능을 사용했는데 오류가 발생했습니다. 어떻게 해결하면 될까요?",
          additionalContext: "사과, 재현 정보 요청, 임시 우회책, 후속 안내를 포함",
        },
        {
          id: "feature",
          label: "추가기능 요청",
          customerMessage: "현재 기능으로는 부족해서 추가 기능이 필요합니다. 검토 가능한지 궁금합니다.",
          additionalContext: "확답 대신 검토 프로세스와 필요한 추가 정보를 정리",
        },
      ],
      settings: {
        project: "프로젝트",
        ai: "AI",
        channel: "채널",
        tone: "톤",
      },
      input: {
        title: "고객 메시지",
        basedOn: "기준",
        projectUnselected: "프로젝트 미선택",
        summarySuffix: "설정으로 고객 응답을 생성합니다.",
        clear: "입력 초기화",
        messagePlaceholder: "고객이 보낸 메시지를 여기에 붙여 넣으세요.",
        additionalPlaceholder: "추가 맥락이 있으면 입력하세요. 예: 결제 이력 확인 완료",
        includeAnalysisTitle: "내부 분석 함께 생성",
        includeAnalysisMessage:
          "켜면 답변 생성과 동시에 내부 분석도 같이 실행합니다. 끄면 필요할 때만 별도로 생성합니다.",
        historyNotice: "응답 생성 후 히스토리에도 바로 저장됩니다.",
        submit: "응답 생성",
        submitting: "응답 생성 중",
        submittingWithAnalysis: "응답·분석 생성 중",
      },
      response: {
        emptyTitle: "아직 생성된 CS 응답이 없습니다.",
        emptyMessage:
          "프로젝트를 고른 뒤 고객 메시지를 입력하고 응답을 생성하면, 여기서 고객 응답과 내부 분석을 바로 확인할 수 있습니다.",
        title: "AI 응답",
        copy: "응답 복사",
        loading: "응답을 생성하는 중입니다...",
        regenerateTone: "톤만 바꿔 재생성",
        regenerateRunner: "AI 바꿔 재생성",
      },
      history: {
        title: "히스토리",
        count: (count: number) => `${count}건`,
        latest: "최신순",
        oldest: "오래된순",
        runner: "AI순",
        empty: "아직 생성 기록이 없습니다.",
        additionalContext: "추가 맥락",
        copy: "복사",
        restore: "다시 보기",
      },
      context: {
        title: "컨텍스트 관리",
        count: (count: number) => `${count}개`,
        hasContext: "있음",
        noContext: "없음",
        path: "경로",
        create: "생성",
      },
    },
    en: {
      eyebrow: "CS Helper",
      heroTitle: "Draft customer replies that stay aligned with each project's real context",
      heroDescription:
        "This view creates customer-facing replies and internal analysis notes from project-specific context. It is meant to prepare practical response options, not just generic AI text.",
      cards: [
        {
          label: "Customer reply",
          title: "Draft the outgoing answer first",
          description: "Handle repeated situations like delays, bug reports, and refund requests much faster.",
        },
        {
          label: "Internal analysis",
          title: "Organize internal notes and reasoning",
          description: "Keep analysis separate from the message you actually send to the customer.",
        },
        {
          label: "Context-aware",
          title: "Keep tone and project context aligned",
          description: "Prepare answers that reflect the selected project's background, channel, and response level.",
        },
      ],
      coreModeTitle: "Simple mode",
      coreModeMessage:
        "Start by choosing one project and entering the customer message. Review the reply draft first, then generate the internal analysis only when you need it.",
      appliedTitle: "Applied",
      projectRequired: "Project required",
      contextReady: "Context ready",
      contextInfoTitle: "Current project baseline",
      workspaceDescription:
        "Enter the customer message to generate a reply. Internal analysis can be added only when needed. If you pick a history item, its original settings and message are restored.",
      quickPresetTitle: "Quick reply presets",
      quickPresetDescription: "Use preset scenarios to drop in a starting draft and adjust it immediately.",
      replyReady: "Reply ready",
      analysisReady: "Analysis ready",
      analysisLoading: "Generating analysis",
      analysisEmpty: "No analysis",
      replyTab: "Customer reply",
      analysisTab: "Internal analysis",
      analysisPanelTitle: "Internal analysis",
      analysisPanelLoading: "Generating internal analysis...",
      analysisRegenerate: "Regenerate analysis",
      analysisHint: "If you did not enable internal analysis during reply generation, you can generate it here later when needed.",
      analysisGenerate: "Generate analysis",
      feedback: {
        responseCreatedWithAnalysis: "Generated the customer reply and internal analysis.",
        responseCreated: "Generated the customer reply.",
        analysisRegenerated: "Regenerated the internal analysis.",
        responseRegeneratedWithAnalysis: "Regenerated the CS reply and internal analysis with the updated settings.",
        responseRegenerated: "Regenerated the CS reply with the updated settings.",
        historyRestored: "Restored the selected history item into the current workspace.",
      },
      errors: {
        responseFailed: "Failed to generate the reply.",
        analysisFailed: "Failed to generate the analysis.",
        regenerateFailed: "Failed to regenerate the response.",
        requestFailed: "Failed to process the request.",
      },
      presets: [
        {
          id: "delay",
          label: "Delay update",
          customerMessage: "Could you confirm when this will be handled? The schedule keeps slipping and it's becoming frustrating.",
          additionalContext: "Explain the reason for the delay transparently and make the next action timing explicit.",
        },
        {
          id: "refund",
          label: "Refund or cancellation",
          customerMessage: "I no longer want to use the service. Please explain the refund or cancellation process.",
          additionalContext: "Avoid overcommitting beyond policy. Focus on verifiable next steps and process.",
        },
        {
          id: "bug",
          label: "Bug report",
          customerMessage: "I just used the feature and ran into an error. How can I fix this?",
          additionalContext: "Include an apology, a request for reproduction details, a temporary workaround, and next-step guidance.",
        },
        {
          id: "feature",
          label: "Feature request",
          customerMessage: "The current feature set is not enough for us. Can you review whether an additional feature is possible?",
          additionalContext: "Do not promise delivery. Explain the review process and what extra details are needed.",
        },
      ],
      settings: {
        project: "Project",
        ai: "AI",
        channel: "Channel",
        tone: "Tone",
      },
      input: {
        title: "Customer message",
        basedOn: "based on",
        projectUnselected: "No project selected",
        summarySuffix: "settings are applied to the generated customer reply.",
        clear: "Clear input",
        messagePlaceholder: "Paste the customer's message here.",
        additionalPlaceholder: "Add any extra context here. Example: Payment history already verified.",
        includeAnalysisTitle: "Generate internal analysis too",
        includeAnalysisMessage:
          "When enabled, internal analysis is generated together with the reply. When disabled, you can generate it later only when you need it.",
        historyNotice: "The generated response is also saved to history right away.",
        submit: "Generate reply",
        submitting: "Generating reply",
        submittingWithAnalysis: "Generating reply and analysis",
      },
      response: {
        emptyTitle: "No CS response has been generated yet.",
        emptyMessage:
          "Choose a project, enter the customer message, and generate a reply. You will be able to review both the outgoing reply and the internal analysis here.",
        title: "AI response",
        copy: "Copy reply",
        loading: "Generating the reply...",
        regenerateTone: "Regenerate with new tone",
        regenerateRunner: "Regenerate with new AI",
      },
      history: {
        title: "History",
        count: (count: number) => `${count} items`,
        latest: "Newest",
        oldest: "Oldest",
        runner: "By AI",
        empty: "No generated history yet.",
        additionalContext: "Additional context",
        copy: "Copy",
        restore: "Restore",
      },
      context: {
        title: "Context manager",
        count: (count: number) => `${count} items`,
        hasContext: "Ready",
        noContext: "Missing",
        path: "Path",
        create: "Create",
      },
    },
  });

  return {
    ...labels,
    getChannelLabel: (channel: CsChannel) => getCsChannelLabel(channel, locale),
    getToneLabel: (tone: CsTone) => getCsToneLabel(tone, locale),
    formatDate: (value: string) => new Date(value).toLocaleString(locale === "en" ? "en-US" : "ko-KR"),
  };
}
