import type { AppLocale } from "@/lib/locale";
import { pickLocale } from "@/lib/locale";

export function getSignalWriterCopy(locale: AppLocale) {
  return pickLocale(locale, {
    ko: {
      eyebrow: "Signal Writer",
      title: "오늘 쓸 만한 기사에서 소셜 초안을 만드는 공간",
      description:
        "Info Hub에서 직접 담아둔 글감을 우선 보여주고, 선택한 것이 없으면 지금 글로 풀기 좋은 기사 5개를 자동 추천합니다.",
      coreMode: "간단 모드에서도 이 탭은 그대로 사용할 수 있습니다.",
      fullMode: "전체 모드에서는 Info Hub와 같이 열어 흐름을 이어가기 좋습니다.",
      autoRefresh: {
        standardBadge: "일반 갱신",
        realtimeBadge: "실시간성 강화",
        standardDescription: "기본은 하루 1회 자동으로 시그널을 새로 읽습니다.",
        realtimeDescription: "앱이 열려 있으면 1시간마다 시그널과 현재 Trend Board를 강제 갱신합니다.",
        switchToRealtime: "실시간성 강화 켜기",
        switchToStandard: "일반 갱신으로 전환",
      },
      refresh: "시그널 새로고침",
      loading: "오늘 쓸 만한 시그널을 고르는 중입니다.",
      loadError: "시그널 목록을 불러오지 못했습니다.",
      empty: "오늘 바로 글로 만들 만한 시그널이 아직 없습니다.",
      entryModes: {
        title: "작성 방식",
        description: "기사 하나로 쓰거나, Trend Board를 열어 랭킹형 글로 바로 변환할 수 있습니다.",
        signal: "개별 시그널",
        board: "Trend Board",
      },
      boards: {
        title: "Trend Board",
        description: "GitHub, npm, frontend, backend, fullstack, skills 보드를 열고 근거 팩을 확인한 뒤 랭킹형 포스트로 변환합니다.",
        presets: "보드 프리셋",
        current: "현재 보드",
        board: "선택한 보드",
        items: "랭킹 후보",
        count: (count: number) => `${count}개 근거 항목`,
        loading: "보드 근거를 모으는 중입니다.",
        loadError: "트렌드 보드를 불러오지 못했습니다.",
        emptyTitle: "아직 보드 항목이 없습니다.",
        emptyMessage: "선택한 보드에서 지금 바로 쓸 만한 근거 항목을 아직 충분히 찾지 못했습니다.",
        reviewerTitle: "근거 검수 기준",
        reviewerMessage: "생성 전에 각 항목의 요약, 원문 컨텍스트, 세부 팩트를 확인하고 포함 여부와 검수 완료를 체크하세요.",
        reviewStatus: "검수 진행",
        reviewProgress: (reviewed: number, included: number, total: number) =>
          `검수 완료 ${reviewed}/${included} · 초안 포함 ${included}/${total}`,
        readySummary: "초안에 포함할 항목만 남기고 모두 검수 완료로 바꾸면 바로 생성할 수 있습니다.",
        excludedSummary: (count: number) => `${count}개 항목은 초안에서 제외된 상태입니다.`,
        reviewRequired: "포함된 항목을 모두 검수 완료로 체크해야 랭킹 글 생성을 시작할 수 있습니다.",
        evidence: "근거 팩",
        facts: "핵심 팩트",
        sourceContext: "원문 컨텍스트",
        sourceDetails: "원문 세부 정보",
        reviewNote: "검수 메모",
        reviewNotePlaceholder: "이 항목을 유지하거나 제외하는 이유, 강조할 팩트, 과장 주의점을 짧게 남기세요.",
        include: "초안 포함",
        reviewed: "검수 완료",
        reviewPending: "검수 필요",
        excluded: "제외됨",
        markAllReviewed: "포함 항목 전체 검수 완료",
        resetReview: "검수 상태 초기화",
        generate: "이 보드로 랭킹 글 생성",
        generatingDescription: "선택한 보드의 항목을 순위 그대로 유지하면서, 근거만으로 랭킹형 포스트 초안을 만드는 중입니다.",
        resultTitle: "Trend Board 초안",
        boardSummary: "보드 요약",
        evidencePack: "생성에 사용한 근거 팩",
        generatedWith: "생성 러너",
        sourceLink: "원문 링크 열기",
      },
      selection: {
        manual: (count: number) => `Info Hub에서 직접 고른 기사 ${count}개를 먼저 보여줍니다.`,
        auto: (count: number) => `직접 고른 기사가 없어 자동 추천 ${count}개를 보여줍니다.`,
        mixed: (manualCount: number, autoCount: number) =>
          `직접 고른 기사 ${manualCount}개를 앞에 두고, 자동 추천 ${autoCount}개를 함께 보강해 보여줍니다.`,
        manualBadge: "직접 선택",
        autoBadge: "자동 추천",
        removeManual: "글감에서 제거",
        clearManual: "직접 선택 전체 비우기",
      },
      setup: {
        title: "현재 생성 설정",
        description: "기사를 고른 뒤 채널, 모드, 러너를 맞추고 바로 초안을 생성합니다.",
        signal: "선택한 기사",
        channel: "게시 채널",
        mode: "현재 모드",
        runner: "현재 러너",
        ready: "바로 생성 가능",
        pending: "먼저 시그널 선택",
        emptyTitle: "아직 선택한 기사가 없습니다.",
        emptyMessage: "왼쪽 목록에서 기사 카드 하나를 고르면, 이 자리에서 생성 설정을 바로 마무리할 수 있습니다.",
      },
      channels: {
        title: "게시 채널",
        description: "같은 기사라도 채널에 따라 문장 길이와 구조, 톤이 달라집니다.",
        threads: {
          label: "Threads",
          description: "대화체 흐름과 저장/공유 톤에 맞춥니다.",
        },
        x: {
          label: "X / Twitter",
          description: "더 짧고 날카로운 훅과 스레드 흐름에 맞춥니다.",
        },
        linkedin: {
          label: "LinkedIn",
          description: "실무형 인사이트와 전문적인 문단 톤에 맞춥니다.",
        },
      },
      pages: {
        select: "1. 시그널 선택",
        generate: "2. 생성 중",
        result: "3. 결과",
      },
      cards: {
        why: "왜 지금 중요한가",
        source: "출처",
        published: "발행 시각",
        selected: "선택됨",
      },
      modes: {
        title: "생성 모드",
        description: "요약형보다 관점형과 바이럴형이 계정 성장에는 더 잘 맞습니다.",
        "news-brief": {
          label: "뉴스 요약형",
          description: "핵심 변화와 의미를 빠르게 정리합니다.",
        },
        insight: {
          label: "인사이트형",
          description: "이 변화가 실무에 미치는 영향을 강조합니다.",
        },
        opinion: {
          label: "의견형",
          description: "내 해석과 판단을 앞세운 글로 만듭니다.",
        },
        viral: {
          label: "바이럴형",
          description: "저장/공유를 부르는 훅과 관점을 우선합니다.",
        },
      },
      recommendation: {
        title: "추천 생성 기준",
        apply: "추천값 적용",
        mode: "추천 모드",
        runner: "추천 러너",
        criteria: "추천 기준",
      },
      research: {
        title: "Research Desk",
        description: "선택한 기사를 Claude와 Codex가 각각 분석해서 화제성, 논쟁 포인트, 실무 영향, 추천 훅을 정리합니다.",
        run: "듀얼 리서치 실행",
        rerun: "리서치 다시 실행",
        running: "Claude + Codex가 리서치 중입니다...",
        apply: "리서치 추천값 적용",
        applied: "리서치 반영됨",
        emptyTitle: "아직 리서치를 돌리지 않았습니다.",
        emptyMessage: "선택한 기사 기준으로 듀얼 리서치를 실행하면, 어떤 각도로 써야 반응이 나올지 먼저 정리합니다.",
        overall: "종합 점수",
        heat: "화제성",
        novelty: "신선도",
        debate: "논쟁성",
        practical: "실무성",
        summary: "종합 해석",
        whyNow: "지금 쓰는 이유",
        bestHook: "추천 훅",
        bestQuestion: "답글 유도 질문",
        sourceContext: "원문 컨텍스트",
        sourceDetails: "원문 세부 정보",
        keyPoints: "핵심 포인트",
        watchouts: "주의점",
        hooks: "후보 훅",
        angles: "추천 각도",
        questions: "질문 포인트",
        claude: "Claude 리서치",
        codex: "Codex 리서치",
        fallback: "fallback",
        unavailable: "사용 불가",
        failed: "실패",
      },
      factCheck: {
        title: "Fact Check",
        description: "현재 초안을 원문 컨텍스트 기준으로 다시 검증합니다. 선택한 모델이 근거 범위를 벗어난 주장, 과장, 불확실한 표현을 찾아 수정 지시를 만듭니다.",
        runner: "검증 모델",
        run: "팩트체크 실행",
        rerun: "팩트체크 다시 실행",
        running: "선택한 모델이 초안을 검증 중입니다...",
        emptyTitle: "아직 팩트체크를 실행하지 않았습니다.",
        emptyMessage: "초안 생성 후 팩트체크를 돌리면, 근거가 약한 주장이나 틀린 표현을 먼저 찾아낼 수 있습니다.",
        verdict: "판정",
        confidence: "신뢰도",
        summary: "검증 요약",
        findings: "검증 항목",
        rewriteBrief: "재생성 수정 지시",
        sourceContext: "검증 근거",
        regenerate: "수정 반영 후 다시 생성",
        pass: "통과",
        mixed: "일부 수정 필요",
        fail: "수정 필요",
        supported: "근거 확인",
        uncertain: "근거 약함",
        incorrect: "틀림",
      },
      runners: {
        title: "AI 생성기 선택",
        description: "직접 원하는 AI를 고르거나, 자동 선택으로 가장 적합한 러너를 쓰게 할 수 있습니다.",
        auto: {
          label: "자동 선택",
          description: "사용 가능한 AI 중 가장 적합한 러너를 고릅니다.",
        },
        claude: {
          label: "Claude",
          description: "훅과 관점형 글에 강합니다.",
        },
        codex: {
          label: "Codex",
          description: "구조화와 실무형 정리에 강합니다.",
        },
        gemini: {
          label: "Gemini",
          description: "빠른 요약과 짧은 초안에 잘 맞습니다.",
        },
        openai: {
          label: "OpenAI",
          description: "API key가 있을 때 쓰는 클라우드 fallback입니다.",
        },
        template: {
          label: "템플릿",
          description: "AI 없이 규칙 기반 초안을 만듭니다.",
        },
        available: "사용 가능",
        unavailable: "준비 필요",
        selected: "선택됨",
        recommended: "추천",
      },
      cta: {
        choose: "이 카드 선택",
        unselect: "선택 해제",
        generate: "선택한 기사로 초안 생성",
        back: "시그널 목록으로 돌아가기",
        regenerate: "다시 생성",
        regenerateWithFactCheck: "팩트 반영 재생성",
      },
      generate: {
        title: "소셜 초안 생성 중",
        description:
          "기사 핵심을 정리하고, 채널에 맞는 각도와 훅, 본문 구조를 묶는 중입니다.",
        processing: "생성 중...",
        done: "생성 완료",
        stages: [
          "기사 신호 정리",
          "핵심 포인트 추출",
          "중복/노이즈 정리",
          "훅과 글 구조 작성",
          "최종 초안 마감",
        ],
      },
      result: {
        title: "생성된 초안",
        channel: "게시 채널",
        mode: "생성 모드",
        runner: "생성 러너",
        angle: "글 각도",
        targetAudience: "이 글이 맞는 독자",
        hook: "훅",
        hookVariants: "훅 3개",
        shortPost: "메인 포스트",
        thread: "연속 포스트",
        replyKit: "댓글 자산",
        firstComment: "첫 댓글",
        followUpReplies: "후속 답글",
        hashtags: "해시태그",
        whyNow: "왜 지금 올리기 좋은가",
        timing: "게시 타이밍",
        primaryWindow: "우선 시간대",
        secondaryWindow: "보조 시간대",
        timingBasis: {
          history: "최근 성과 기록 기준",
          default: "기본 권장 기준",
        },
        postingTips: "올릴 때 팁",
        currentHook: "현재 훅",
        rewriteFromHook: "이 훅으로 다시 쓰기",
        performance: {
          title: "게시 성과 기록",
          description:
            "실제 반응 숫자를 남겨두면 다음에 어떤 훅과 기사 조합이 먹히는지 다시 판단하는 기준으로 쓸 수 있습니다.",
          currentHook: "기준 훅",
          postUrl: "게시 링크",
          postUrlPlaceholder: "https://threads.com/... 또는 https://x.com/...",
          postedAt: "실제 게시 시각",
          views: "조회수",
          likes: "좋아요",
          replies: "답글",
          reposts: "공유",
          saves: "저장",
          notes: "메모",
          notesPlaceholder: "왜 반응이 좋았는지, 첫 댓글 전략 등을 짧게 남겨두세요.",
          save: "성과 저장",
          saving: "성과 저장 중...",
          saveError: "성과 기록을 저장하지 못했습니다.",
          latestSaved: "가장 최근에 저장한 성과",
          savedCount: (count: number) => `저장 기록 ${count}건`,
        },
        quality: "바이럴 품질 점수",
        qualityTotal: "총점",
        qualityLevels: {
          rough: "초안 수준",
          solid: "게시 가능",
          strong: "강한 초안",
        },
        source: "원문 출처",
        sourceLink: "원문 링크",
        publishedAt: "발행 시각",
        visuals: "업로드용 이미지",
        sourceImage: "원문 참고 이미지",
        generatedCover: "자동 생성 커버",
        sourceImageHint: "원문에 붙은 대표 이미지가 있을 때만 참고용으로 보여줍니다.",
        generatedCoverHint: "이 커버는 지금 글의 각도에 맞춰 자동 생성한 업로드용 이미지입니다.",
        visualStrategy: "이미지 방향",
        openOriginal: "원문 링크 열기",
        openSourceImage: "원문 이미지 열기",
        downloadCover: "커버 다운로드",
        noSourceImage: "이 시그널에는 바로 쓸 수 있는 원문 이미지가 없습니다.",
        saved: "로컬 저장 경로",
        sourceModels: {
          claude: "Claude 생성",
          codex: "Codex 생성",
          gemini: "Gemini 생성",
          openai: "OpenAI 생성",
          template: "템플릿 생성",
        },
        copyShort: "메인 포스트 복사",
        copyThread: "연속 포스트 복사",
        copyHook: "훅 복사",
        copyComment: "첫 댓글 복사",
        copyReplies: "후속 답글 복사",
      },
    },
    en: {
      eyebrow: "Signal Writer",
      title: "Turn daily news signals into social-ready drafts",
      description:
        "Signal Writer shows the stories you explicitly saved from Info Hub first. When nothing is saved, it falls back to five auto-ranked stories worth writing about now.",
      coreMode: "This tab stays useful even in simple mode.",
      fullMode: "In full mode, it works especially well next to Info Hub.",
      autoRefresh: {
        standardBadge: "Standard refresh",
        realtimeBadge: "Realtime boost",
        standardDescription: "By default, Signal Writer auto-refreshes once per day.",
        realtimeDescription: "While the app stays open, it force-refreshes signals and the current Trend Board every hour.",
        switchToRealtime: "Enable realtime boost",
        switchToStandard: "Use standard refresh",
      },
      refresh: "Refresh signals",
      loading: "Picking the best signals for today.",
      loadError: "Failed to load the signal list.",
      empty: "There are no strong signals to write from right now.",
      entryModes: {
        title: "Writing mode",
        description: "Write from one saved signal or open a Trend Board and turn the ranked evidence pack into a post.",
        signal: "Single signal",
        board: "Trend Board",
      },
      boards: {
        title: "Trend Board",
        description: "Open GitHub, npm, frontend, backend, fullstack, and skills boards, review the evidence pack, and turn it into a ranked post.",
        presets: "Board presets",
        current: "Current board",
        board: "Selected board",
        items: "Ranked candidates",
        count: (count: number) => `${count} evidence item(s)`,
        loading: "Collecting the board evidence pack.",
        loadError: "Failed to load the trend board.",
        emptyTitle: "There are no usable board items yet.",
        emptyMessage: "The selected board does not have enough strong evidence items to compile right now.",
        reviewerTitle: "Evidence review rule",
        reviewerMessage: "Check each summary, source context, and fact detail before generating, then mark whether the item stays in the draft and whether review is complete.",
        reviewStatus: "Review progress",
        reviewProgress: (reviewed: number, included: number, total: number) =>
          `Reviewed ${reviewed}/${included} · Included ${included}/${total}`,
        readySummary: "Keep only the items you want in the draft, then mark each included item as reviewed before generating.",
        excludedSummary: (count: number) => `${count} item(s) are currently excluded from the ranked draft.`,
        reviewRequired: "Every included item must be marked as reviewed before the ranked post can be generated.",
        evidence: "Evidence pack",
        facts: "Key facts",
        sourceContext: "Source context",
        sourceDetails: "Source details",
        reviewNote: "Review note",
        reviewNotePlaceholder: "Leave a short note about why this item stays or goes, which fact matters most, or what wording should stay cautious.",
        include: "Include in draft",
        reviewed: "Reviewed",
        reviewPending: "Needs review",
        excluded: "Excluded",
        markAllReviewed: "Mark all included items reviewed",
        resetReview: "Reset review state",
        generate: "Generate ranked post from this board",
        generatingDescription: "Compiling a ranked post from the selected board while keeping the evidence and ranking order intact.",
        resultTitle: "Trend Board draft",
        boardSummary: "Board summary",
        evidencePack: "Evidence pack used for the draft",
        generatedWith: "Generated with",
        sourceLink: "Open source link",
      },
      selection: {
        manual: (count: number) => `Showing ${count} stories you picked from Info Hub first.`,
        auto: (count: number) => `No saved picks yet, so showing ${count} auto-ranked stories.`,
        mixed: (manualCount: number, autoCount: number) =>
          `Showing your ${manualCount} picked stories first, plus ${autoCount} auto-ranked signals to widen the posting pool.`,
        manualBadge: "Picked",
        autoBadge: "Auto-ranked",
        removeManual: "Remove from picks",
        clearManual: "Clear picked stories",
      },
      setup: {
        title: "Current draft setup",
        description: "Choose the story first, then confirm the channel, mode, and runner before generating the draft.",
        signal: "Selected story",
        channel: "Target channel",
        mode: "Current mode",
        runner: "Current runner",
        ready: "Ready to generate",
        pending: "Choose a signal first",
        emptyTitle: "No story is selected yet.",
        emptyMessage: "Pick one card from the list on the left, then finish the draft setup here.",
      },
      channels: {
        title: "Target channel",
        description: "The same story should be framed differently depending on where you plan to publish it.",
        threads: {
          label: "Threads",
          description: "Best for conversational flow and save/share-friendly pacing.",
        },
        x: {
          label: "X / Twitter",
          description: "Best for tighter hooks and sharper sequenced posts.",
        },
        linkedin: {
          label: "LinkedIn",
          description: "Best for practical insight and a more professional tone.",
        },
      },
      pages: {
        select: "1. Select Signal",
        generate: "2. Generating",
        result: "3. Result",
      },
      cards: {
        why: "Why this matters now",
        source: "Source",
        published: "Published",
        selected: "Selected",
      },
      modes: {
        title: "Draft mode",
        description: "Insight, opinion, and viral modes usually perform better than a plain summary.",
        "news-brief": {
          label: "News brief",
          description: "Fast summary of what changed and why it matters.",
        },
        insight: {
          label: "Insight",
          description: "Translate the signal into workflow impact.",
        },
        opinion: {
          label: "Opinion",
          description: "Lead with your take instead of the headline.",
        },
        viral: {
          label: "Viral",
          description: "Optimize for hook strength and shareability.",
        },
      },
      recommendation: {
        title: "Recommended setup",
        apply: "Use recommendation",
        mode: "Recommended mode",
        runner: "Recommended runner",
        criteria: "Why this setup",
      },
      research: {
        title: "Research Desk",
        description: "Claude and Codex each analyze the selected story to surface what could make it timely, debatable, practical, and worth posting.",
        run: "Run dual research",
        rerun: "Run research again",
        running: "Claude + Codex are researching this signal...",
        apply: "Use research recommendation",
        applied: "Research applied",
        emptyTitle: "No research has been run yet.",
        emptyMessage: "Run dual research on the selected story first to see which angle is most likely to create reaction.",
        overall: "Overall",
        heat: "Heat",
        novelty: "Novelty",
        debate: "Debate",
        practical: "Practical",
        summary: "Combined read",
        whyNow: "Why now",
        bestHook: "Recommended hook",
        bestQuestion: "Reply-driving question",
        sourceContext: "Source context",
        sourceDetails: "Source details",
        keyPoints: "Key points",
        watchouts: "Watchouts",
        hooks: "Hook options",
        angles: "Angle options",
        questions: "Question options",
        claude: "Claude research",
        codex: "Codex research",
        fallback: "fallback",
        unavailable: "unavailable",
        failed: "failed",
      },
      factCheck: {
        title: "Fact Check",
        description: "Re-check the generated draft against the original source context. The selected model flags unsupported claims, overstatements, and factual drift before you regenerate.",
        runner: "Fact-check model",
        run: "Run fact check",
        rerun: "Run fact check again",
        running: "The selected model is fact-checking this draft...",
        emptyTitle: "No fact check has been run yet.",
        emptyMessage: "After generating a draft, run fact check once more to catch unsupported claims before you publish or regenerate.",
        verdict: "Verdict",
        confidence: "Confidence",
        summary: "Fact-check summary",
        findings: "Findings",
        rewriteBrief: "Rewrite brief",
        sourceContext: "Evidence base",
        regenerate: "Regenerate with fixes",
        pass: "Pass",
        mixed: "Needs revision",
        fail: "Fail",
        supported: "Supported",
        uncertain: "Uncertain",
        incorrect: "Incorrect",
      },
      runners: {
        title: "AI runner",
        description: "Pick a specific AI writer, or let the app choose the best available runner automatically.",
        auto: {
          label: "Auto",
          description: "Choose the best available runner for this draft.",
        },
        claude: {
          label: "Claude",
          description: "Best for hooks and stronger point of view.",
        },
        codex: {
          label: "Codex",
          description: "Best for structured, practical drafts.",
        },
        gemini: {
          label: "Gemini",
          description: "Best for fast summaries and concise first drafts.",
        },
        openai: {
          label: "OpenAI",
          description: "Cloud fallback when the API key is configured.",
        },
        template: {
          label: "Template",
          description: "Rule-based fallback without AI.",
        },
        available: "Available",
        unavailable: "Needs setup",
        selected: "Selected",
        recommended: "Recommended",
      },
      cta: {
        choose: "Choose this card",
        unselect: "Clear selection",
        generate: "Generate draft from selected signal",
        back: "Back to signals",
        regenerate: "Generate again",
        regenerateWithFactCheck: "Regenerate with fact check",
      },
      generate: {
        title: "Generating your social draft",
        description:
          "The app is extracting the core signal, shaping the angle, and writing a channel-ready version.",
        processing: "Generating...",
        done: "Done",
        stages: [
          "Collecting the signal",
          "Extracting key points",
          "Removing noise and overlap",
          "Writing the hook and body",
          "Finalizing the post",
        ],
      },
      result: {
        title: "Generated draft",
        channel: "Target channel",
        mode: "Draft mode",
        runner: "AI runner",
        angle: "Post angle",
        targetAudience: "Best audience",
        hook: "Hook",
        hookVariants: "Three hook options",
        shortPost: "Primary post",
        thread: "Series version",
        replyKit: "Reply kit",
        firstComment: "First comment",
        followUpReplies: "Follow-up replies",
        hashtags: "Hashtags",
        whyNow: "Why this is timely",
        timing: "Posting timing",
        primaryWindow: "Primary window",
        secondaryWindow: "Backup window",
        timingBasis: {
          history: "Based on recent performance logs",
          default: "Default recommendation",
        },
        postingTips: "Posting tips",
        currentHook: "Current hook",
        rewriteFromHook: "Rewrite from this hook",
        performance: {
          title: "Post performance log",
          description:
            "Save the real numbers after posting so the next round can learn which hook and signal mix actually worked.",
          currentHook: "Active hook",
          postUrl: "Post URL",
          postUrlPlaceholder: "https://threads.com/... or https://x.com/...",
          postedAt: "Actual post time",
          views: "Views",
          likes: "Likes",
          replies: "Replies",
          reposts: "Reposts",
          saves: "Saves",
          notes: "Notes",
          notesPlaceholder: "Add a short note about timing, replies, or why this one worked.",
          save: "Save performance",
          saving: "Saving performance...",
          saveError: "Failed to save the performance log.",
          latestSaved: "Latest saved performance",
          savedCount: (count: number) => `${count} saved log(s)`,
        },
        quality: "Virality score",
        qualityTotal: "Total",
        qualityLevels: {
          rough: "Needs work",
          solid: "Postable",
          strong: "Strong draft",
        },
        source: "Original source",
        sourceLink: "Source link",
        publishedAt: "Published",
        visuals: "Upload-ready visuals",
        sourceImage: "Source reference image",
        generatedCover: "Generated cover card",
        sourceImageHint: "Shown only when the original article exposes a usable reference image.",
        generatedCoverHint: "This cover is generated from the post angle so you can upload it directly.",
        visualStrategy: "Visual direction",
        openOriginal: "Open original article",
        openSourceImage: "Open source image",
        downloadCover: "Download cover",
        noSourceImage: "This signal does not expose a usable source image.",
        saved: "Saved locally",
        sourceModels: {
          claude: "Generated with Claude",
          codex: "Generated with Codex",
          gemini: "Generated with Gemini",
          openai: "Generated with OpenAI",
          template: "Generated with template fallback",
        },
        copyShort: "Copy primary post",
        copyThread: "Copy series",
        copyHook: "Copy hook",
        copyComment: "Copy first comment",
        copyReplies: "Copy follow-up replies",
      },
    },
  });
}
