// Core call-to-PRD UI copy tree (viewer, intake, guide, etc.).
export const baseCopy = {
  ko: {
    common: {
      none: "없음",
      custom: "커스텀",
      allProjects: "모든 프로젝트",
      retry: "재시도",
      delete: "삭제",
      copy: "복사",
      download: "다운로드",
      loading: "생성 중",
      ready: "준비됨",
      create: "생성",
      required: "필수",
      selected: "선택됨",
      available: "선택 가능",
      active: "사용 중",
      currentWorkspace: "현재 작업중",
      documentCount: (count: number) => `${count}개 문서`,
    },
    intake: {
      coreModeTitle: "간단 모드 안내",
      coreModeMessage:
        "처음에는 텍스트 직접 입력으로 시작하는 편이 가장 단순합니다. 회의 메모나 고객 이슈 설명을 붙여넣고 프로젝트만 선택한 뒤 문서 생성 시작을 누르면 됩니다.",
      feedbackTitle: "반영되었습니다",
      quickBadge: "빠른 작성",
      quickTitle: "한 줄 입력으로 PRD 1장을 바로 만듭니다.",
      quickDescription:
        "회의 메모, 고객 요청, 운영 이슈를 한두 문장으로 적으면 PRD 초안을 먼저 만듭니다. 세부 메타데이터와 추가 문서가 필요하면 정밀 모드로 전환하면 됩니다.",
      quickTopicLabel: "주제 / 요청 요약",
      quickTopicPlaceholder: "예: 결제 실패 VOC를 정리해서 원인 가설과 대응 방향이 포함된 PRD 초안을 만들어줘",
      quickTopicHint: "통화 전체를 붙일 필요는 없습니다. 지금 정리하고 싶은 이슈나 목표만 한 줄로 적어도 시작할 수 있습니다.",
      quickVoiceHint: "고객 통화나 회의 녹음을 올리면 기존 전사 파이프라인으로 바로 PRD를 만듭니다.",
      quickVoiceSelected: (name: string) => `선택한 음성 파일: ${name}`,
      quickInputPriorityHint: "텍스트 메모가 함께 있어도 음성 파일을 우선 처리합니다.",
      quickProjectLabel: "프로젝트 기준선",
      quickProjectDescription: "프로젝트는 선택 사항이지만, 선택하면 실제 코드베이스와 문서를 읽어 PRD 문맥을 보강합니다.",
      quickProjectPlaceholder: "프로젝트 선택 안 함 (현재 워크스페이스 우선)",
      quickProjectStatus: "현재 기준선",
      quickProjectOptional: "프로젝트 미선택",
      quickCurrentWorkspace: "현재 작업중인 워크스페이스를 자동 기준선으로 사용합니다.",
      quickContextHint: "프로젝트를 선택하면 읽은 기준 파일과 요약이 여기에 표시됩니다.",
      quickOutputBadge: "생성 결과",
      quickOutputTitle: "Quick 모드는 PRD 1장에 집중합니다.",
      quickPresetTitle: "프리셋",
      quickModeTitle: "생성 엔진",
      quickDeliverableTitle: "산출물",
      quickDeliverableValue: "PRD 1장",
      quickSubmit: "빠르게 PRD 생성",
      quickSubmitHint: "현재 AI 모드는 유지한 채 Quick preset과 PRD 단일 출력만 적용합니다.",
      fileMode: "녹음 파일",
      textMode: "내용 직접 입력",
      filePlaceholder: "녹음 파일을 드래그하거나 클릭 (.m4a .mp3 .wav .webm, 최대 50MB)",
      textPlaceholder: "고객 불만, 회의 메모, 통화 내용, 운영 이슈를 여기에 붙여넣기...",
      pdfPlaceholder: "참고 PDF 첨부 (워크북/양식, 선택, 최대 20MB)",
      pdfAttached: (name: string) => `첨부 PDF: ${name}`,
      projectSelectPlaceholder: "로컬 프로젝트 선택 (필수)",
      projectNamePlaceholder: "프로젝트명 (표시용)",
      customerNamePlaceholder: "고객명 (선택)",
      additionalContextPlaceholder: "추가 맥락 (선택)",
      projectContextTitle: "프로젝트 컨텍스트 확인",
      projectContextDescription: "선택한 프로젝트를 실제로 읽어 PRD 생성 기준선으로 사용합니다.",
      projectContextReady: "프로젝트 기준선 준비 완료",
      projectContextLoading: "프로젝트 컨텍스트를 스캔하는 중입니다.",
      projectContextFailed: "프로젝트 컨텍스트를 준비하지 못했습니다.",
      projectContextSources: "읽은 기준 파일",
      projectContextSummary: "요약 미리보기",
      structuringTitle: "입력 구조화",
      structuringDescription:
        "입력 유형과 문제 강도를 같이 주면 문제정의서, PRD, 고객 공유 문서의 톤과 우선순위 판단이 더 안정적으로 나옵니다.",
      inputKind: "입력 유형",
      severity: "심각도",
      impact: "영향 범위",
      urgency: "긴급도",
      reproducibility: "재현 상태",
      workaroundPlaceholder: "현재 우회책 또는 임시 대응이 있으면 입력",
      externalDocsTitle: "고객 공유 문서 분리",
      externalDocsDescription: "켜면 고객 전달용 문서에서 내부 메모와 원인 가설을 제외합니다.",
      selectedProjectPrompt:
        "선택한 프로젝트의 문서, 설정, 핵심 엔트리포인트를 실제로 읽어 문서 생성 프롬프트에 기준선으로 반영합니다.",
      currentWorkspaceHint: "현재 이 워크스페이스를 기준으로 문서를 생성합니다.",
      baselineTitle: "변경 비교 기준 문서",
      baselineDescription:
        "선택하면 해당 저장 문서를 기준선으로 비교하고, 비워두면 같은 프로젝트의 최신 저장 문서를 자동 선택합니다.",
      baselineAutoOption: "자동 선택 (같은 프로젝트 최신 저장 문서)",
      baselineAutoButton: "자동 기준선 사용",
      queueTitle: "작업 큐",
      queueDescription: "현재 생성 중인 작업과 최근 완료 작업을 한 화면에서 확인합니다.",
      inProgress: "진행중",
      recentComplete: "최근 완료",
      noActiveQueue: "진행 중인 작업이 없습니다.",
      noRecentQueue: "최근 완료 작업이 없습니다.",
      templateTitle: "프로젝트 템플릿 세트",
      templateDescription: "현재 문서 조합을 프로젝트별 템플릿으로 저장해 반복 요청에 재사용할 수 있습니다.",
      saveCurrentConfig: "현재 구성 저장",
      noTemplateSets: "저장된 템플릿 세트가 없습니다. 자주 쓰는 문서 구성을 저장해 두면 운영 기능 추가나 AI 검수 요청에 바로 재사용할 수 있습니다.",
      applyThisConfig: "이 구성 적용",
      primaryPresetsTitle: "기본 프리셋",
      advancedPresetsTitle: "고급 프리셋",
      advancedPresetsShow: "고급 프리셋 보기",
      advancedPresetsHide: "고급 프리셋 숨기기",
      wizardBack: "이전",
      wizardNext: "다음",
      wizardStepLabel: "단계",
      wizardSteps: [
        { title: "입력 소스", description: "음성 파일, PDF, 직접 입력 메모와 프로젝트 기준선을 준비합니다." },
        { title: "문서 구성", description: "프리셋과 문서 조합을 정하고 템플릿 세트를 바로 적용합니다." },
        { title: "세부 맥락", description: "프리셋에 따라 필요한 메타데이터만 좁혀서 확인합니다." },
      ],
      generationTitle: "문서 생성 구성",
      generationDescription:
        "내부는 문서별로 따로 생성하고, 여기서는 프리셋으로 한 번에 선택하거나 필요한 문서만 커스텀으로 고를 수 있습니다.",
      viewGuide: "선택 가이드 보기",
      selectedDocs: (count: number) => `선택 문서 ${count}개`,
      startGeneration: "문서 생성 시작",
      emptyTitle: "첫 문서 번들을 아직 만들지 않았습니다.",
      emptyMessage:
        "녹음 파일, 회의 메모, 고객 불만 내용을 넣고 문서 구성을 고르면, PRD와 문제정의서, 고객 공유 문서, 저장 구조, 다음 액션까지 한 흐름으로 이어집니다.",
      emptyAction: "선택 가이드 보기",
    },
    viewer: {
      uploadDone: "파일 업로드 완료",
      audioToText: "음성→텍스트 변환",
      pdfExtract: "PDF 텍스트 추출",
      pdfAnalyze: "PDF 구조 분석",
      dualMerge: "Dual-AI 머지",
      workingDocs: "실무 문서 생성",
      completed: "완료",
      failedTitle: "문서 생성이 중단되었습니다",
      noticeTitle: "진행 상태를 불러오지 못했습니다",
      docResultsTitle: "문서 결과",
      docResultsDescription: "PRD와 생성된 지원 문서를 문서별로 열고, 현재 본문은 필요할 때만 펼쳐서 볼 수 있습니다.",
      copyCurrentDoc: "현재 문서 복사",
      downloadMarkdown: ".md 다운로드",
      mergedPrd: "통합 PRD",
      diffReport: "차이점",
      warningPrefix: "일부 문서는 생성되지 않았습니다:",
      baselinePrefix: "변경 비교 기준 문서:",
      collapseBody: "본문을 접습니다.",
      expandBody: "본문을 펼쳐서 전체 내용을 확인합니다.",
      sectionCardsTitle: "섹션 카드",
      sectionCardsDescription: "각 섹션을 카드 단위로 검토하고 필요한 부분만 다시 생성할 수 있습니다.",
      regenerateSection: "다시 생성",
      regenerateSectionHint: "힌트 추가 (선택)",
      regenerateSectionPlaceholder: "예: 고객 영향과 운영 롤백 기준을 더 구체적으로 써줘",
      regenerateSectionSubmit: "이 섹션 다시 생성",
      regenerateSectionCancel: "취소",
      regenerateUnavailable: "통합 PRD 또는 저장된 지원 문서에서만 섹션 재생성을 지원합니다.",
      savedTreeTitle: "저장 구조",
      savedTreeDescription: "저장된 PRD 번들 아래 문서와 `next-actions` 파일을 트리처럼 다시 열어볼 수 있습니다.",
      currentBundle: "현재 PRD 번들",
      artifacts: "artifacts/",
      nextActions: "next-actions/",
      noSavedNextActions: "아직 저장된 다음 액션이 없습니다.",
      nextActionsTitle: "다음 액션",
      nextActionsDescription: "PRD를 바탕으로 PM / FE / BE / QA / CS / GitHub Issue 초안을 이어서 생성합니다.",
      quickActionsEyebrow: "바로 이어서",
      quickActionsTitle: "결과를 다음 작업으로 바로 넘기기",
      quickActionsDescription: "가장 많이 쓰는 후속 흐름을 위로 올렸습니다. PM/FE 초안은 바로 열고, Obsidian과 GitHub 이슈 초안은 한 번에 보냅니다.",
      quickActionGenerate: "생성",
      quickActionOpen: "열기",
      quickActionReady: "이미 초안이 준비되어 있습니다.",
      quickActionGenerateHint: "현재 PRD로 새 초안을 만듭니다.",
      obsidianCardTitle: "옵시디언 노트로 보내기",
      obsidianCardDescription: "통합 PRD를 Obsidian vault의 Inbox 또는 vault 루트에 바로 저장합니다.",
      obsidianCardCta: "Obsidian 저장",
      obsidianSetupCta: "vault 경로 설정",
      obsidianSetupHint: "runtime settings 파일에 `paths.obsidianVault`를 설정하면 export를 활성화할 수 있습니다.",
      obsidianTargetLabel: "저장 위치:",
      githubIssueCardTitle: "GitHub Issue 초안 복사",
      githubIssueCardDescription: "PRD를 요약해서 이슈 본문 형식으로 클립보드에 복사합니다.",
      githubIssueCardHint: "gh CLI 없이 복사만 수행합니다.",
      githubIssueCardCta: "이슈 초안 복사",
      actionDraftCopy: "초안 복사",
      actionDraftDownload: "초안 다운로드",
      collapseDraft: "초안 본문을 접습니다.",
      expandDraft: "초안 본문을 펼쳐서 전체 내용을 확인합니다.",
      noActionDraftYet: "역할별 버튼을 누르면 현재 PRD와 지원 문서를 바탕으로 다음 액션 초안을 생성합니다.",
      noClaudeResult: "(Claude 결과 없음)",
      noCodexResult: "(Codex 결과 없음)",
      noDiffResult: "(차이점 리포트 없음)",
      noProjectContextWarning: "legacy bundle / no project context",
    },
    history: {
      currentSession: "현재 세션",
      savedDocs: "저장된 문서",
      searchSaved: "저장된 문서 검색",
      legacy: "legacy",
      hasBaseline: "기준선 있음",
      noSearchResult: "검색 결과가 없습니다.",
      page: (current: number, total: number) => `${current} / ${total} 페이지`,
      prev: "이전",
      next: "다음",
      projectUnset: "프로젝트 미지정",
    },
    guide: {
      closeAria: "가이드 닫기",
      badge: "선택 가이드",
      title: "언제 어떤 문서를 선택할지 빠르게 판단하기",
      description: "문서를 많이 뽑을수록 좋은 게 아니라, 현재 단계에 맞는 세트를 고르는 게 중요합니다.",
      tabs: {
        presets: "프리셋별",
        docs: "문서별",
        scenarios: "추천 시나리오",
      },
      applyPreset: "이 프리셋 적용",
      chooseWhen: "이런 경우 선택",
      skipWhen: "지금은 보류해도 되는 경우",
      useLabel: "기본 추천",
      extraLabel: "추가 추천",
      flowTitle: "기본 흐름 정리",
      flowSteps: [
        "1. 현재 단계에 맞는 프리셋이나 문서를 선택합니다.",
        "2. 결과 화면에서 PRD와 지원 문서를 확인합니다.",
        "3. 저장 구조에서 저장된 문서와 `next-actions`를 다시 엽니다.",
        "4. 다음 액션에서 PM / FE / BE / QA / CS 후속 문서를 이어서 생성합니다.",
      ],
    },
    hooks: {
      submitStarted: "문서 생성 작업이 시작되었습니다. 완료되면 저장 구조와 다음 액션에서 이어서 사용할 수 있습니다.",
      submitMissingInput: "녹음 파일을 올리거나 텍스트 메모를 입력한 뒤 다시 시도해 주세요.",
      projectRequired: "프로젝트를 선택하고 컨텍스트 준비가 완료된 뒤 다시 시도해 주세요.",
      projectContextNotReady: "프로젝트 컨텍스트가 아직 준비되지 않았습니다. 잠시 후 다시 시도해 주세요.",
      submitFailed: "문서 생성을 시작하지 못했습니다. 입력값과 로컬 실행 환경을 확인한 뒤 다시 시도해 주세요.",
      nextActionSaved: (title: string) => `${title} 초안을 저장 구조 아래 next-actions에 저장했습니다.`,
      nextActionCreated: (title: string) => `${title} 초안을 생성했습니다.`,
      nextActionFailed: "다음 액션 초안 생성에 실패했습니다. 잠시 후 다시 시도해 주세요.",
      obsidianExported: (filePath: string | null) => filePath ? `옵시디언 노트를 저장했습니다: ${filePath}` : "옵시디언 노트를 저장했습니다.",
      obsidianExportFailed: "옵시디언 export에 실패했습니다. vault 경로 설정과 쓰기 권한을 확인해 주세요.",
      githubIssueCopied: "GitHub Issue 초안을 클립보드에 복사했습니다.",
      githubIssueCopyFailed: "GitHub Issue 초안 복사에 실패했습니다. 다시 시도해 주세요.",
      saveTemplateTitle: "템플릿 세트 저장",
      saveTemplateMessage: "현재 문서 구성과 생성 모드를 템플릿 세트로 저장합니다.",
      saveTemplatePlaceholder: "템플릿 세트 이름을 입력하세요.",
      saveTemplateInitial: (projectName?: string) => (projectName ? `${projectName} 기본 세트` : "내 템플릿"),
      saveLabel: "저장",
      templateSaved: "현재 문서 구성을 템플릿 세트로 저장했습니다.",
      templateDeleted: "템플릿 세트를 삭제했습니다.",
      deleteTemplateTitle: "템플릿 세트 삭제",
      deleteTemplateMessage: "이 템플릿 세트를 삭제할까요?",
      deleteSavedBundleTitle: "저장된 문서 삭제",
      deleteSavedBundleMessage: "저장된 문서 번들과 next-actions를 함께 삭제할까요?",
      savedBundleDeleted: "저장된 문서를 삭제했습니다.",
      deleteHistoryTitle: "현재 세션 기록 삭제",
      deleteHistoryMessage: "현재 세션 기록을 삭제할까요?",
      historyDeleted: "현재 세션 기록을 삭제했습니다.",
      retryTextRestored: "입력값을 복원했습니다. 내용 확인 후 다시 문서 생성을 시작하세요.",
      retrySettingsRestored: "설정값을 복원했습니다. 원본 오디오/PDF 파일은 다시 첨부한 뒤 재시도하세요.",
      deleteFailed: "삭제 중 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.",
      sectionRegenerated: (title: string) => `${title} 섹션을 다시 생성했습니다.`,
      sectionRegenerateFailed: "섹션 다시 생성에 실패했습니다. 잠시 후 다시 시도해 주세요.",
    },
  },
  en: {
    common: {
      none: "None",
      custom: "Custom",
      allProjects: "All projects",
      retry: "Retry",
      delete: "Delete",
      copy: "Copy",
      download: "Download",
      loading: "Generating",
      ready: "Ready",
      create: "Generate",
      required: "Required",
      selected: "Selected",
      available: "Available",
      active: "Active",
      currentWorkspace: "Current workspace",
      documentCount: (count: number) => `${count} docs`,
    },
    intake: {
      coreModeTitle: "Simple mode tip",
      coreModeMessage:
        "Starting with direct text input is the simplest path. Paste meeting notes or a customer issue, choose a project, and start generating docs.",
      feedbackTitle: "Applied",
      quickBadge: "Quick mode",
      quickTitle: "Turn a one-line topic into a PRD immediately.",
      quickDescription:
        "Write one or two sentences about the meeting note, customer request, or ops issue and start with a PRD draft first. Switch to Pro mode when you need metadata and extra working docs.",
      quickTopicLabel: "Topic / request summary",
      quickTopicPlaceholder: "Example: Draft a PRD for payment-failure VOC with root-cause hypotheses and response direction",
      quickTopicHint: "You do not need the full transcript. A short topic or issue summary is enough to start.",
      quickVoiceHint: "Upload a client call or meeting recording to reuse the existing transcription pipeline.",
      quickVoiceSelected: (name: string) => `Selected audio file: ${name}`,
      quickInputPriorityHint: "If both text and audio are present, the audio file is used first.",
      quickProjectLabel: "Project baseline",
      quickProjectDescription: "Project selection is optional, but when selected the actual codebase and docs are used as the PRD baseline.",
      quickProjectPlaceholder: "No project selected (prefer current workspace)",
      quickProjectStatus: "Current baseline",
      quickProjectOptional: "No project selected",
      quickCurrentWorkspace: "The current workspace is being used as the automatic baseline.",
      quickContextHint: "When a project is selected, the scanned baseline files and summary appear here.",
      quickOutputBadge: "Output",
      quickOutputTitle: "Quick mode focuses on a single PRD.",
      quickPresetTitle: "Preset",
      quickModeTitle: "Generation engine",
      quickDeliverableTitle: "Deliverable",
      quickDeliverableValue: "One PRD",
      quickSubmit: "Generate PRD quickly",
      quickSubmitHint: "Keeps your current AI mode and applies only the Quick preset with PRD output.",
      fileMode: "Audio file",
      textMode: "Direct text",
      filePlaceholder: "Drag or click to upload audio (.m4a .mp3 .wav .webm, up to 50MB)",
      textPlaceholder: "Paste customer complaints, meeting notes, call content, or ops issues here...",
      pdfPlaceholder: "Attach reference PDF (optional, up to 20MB)",
      pdfAttached: (name: string) => `Attached PDF: ${name}`,
      projectSelectPlaceholder: "Select a local project (required)",
      projectNamePlaceholder: "Project name (display only)",
      customerNamePlaceholder: "Customer name (optional)",
      additionalContextPlaceholder: "Additional context (optional)",
      projectContextTitle: "Project context check",
      projectContextDescription: "The selected project is scanned and used as the PRD baseline.",
      projectContextReady: "Project baseline is ready",
      projectContextLoading: "Scanning the selected project context.",
      projectContextFailed: "Failed to prepare the project context.",
      projectContextSources: "Files used as baseline",
      projectContextSummary: "Summary preview",
      structuringTitle: "Input structure",
      structuringDescription:
        "Providing issue type and severity helps the system produce more stable tone and prioritization across problem statements, PRDs, and client docs.",
      inputKind: "Input type",
      severity: "Severity",
      impact: "Customer impact",
      urgency: "Urgency",
      reproducibility: "Reproducibility",
      workaroundPlaceholder: "Current workaround or temporary response",
      externalDocsTitle: "Separate client-facing docs",
      externalDocsDescription: "When enabled, client-facing docs omit internal notes and root-cause hypotheses.",
      selectedProjectPrompt:
        "The selected project's docs, config, and key entrypoints are read and used as the generation baseline.",
      currentWorkspaceHint: "Documents will be generated against the current workspace.",
      baselineTitle: "Baseline document for comparison",
      baselineDescription:
        "Choose a saved document as the comparison baseline, or leave it blank to auto-pick the latest doc from the same project.",
      baselineAutoOption: "Auto-select latest saved doc for this project",
      baselineAutoButton: "Use auto baseline",
      queueTitle: "Work queue",
      queueDescription: "See active generation jobs and recently completed jobs in one place.",
      inProgress: "In progress",
      recentComplete: "Recent complete",
      noActiveQueue: "No active jobs.",
      noRecentQueue: "No recently completed jobs.",
      templateTitle: "Project template sets",
      templateDescription: "Save the current doc mix as a reusable template set for repeated requests.",
      saveCurrentConfig: "Save current setup",
      noTemplateSets: "No saved template sets yet. Save a document mix to reuse it for recurring ops or AI QA requests.",
      applyThisConfig: "Apply this setup",
      primaryPresetsTitle: "Primary presets",
      advancedPresetsTitle: "Advanced presets",
      advancedPresetsShow: "Show advanced presets",
      advancedPresetsHide: "Hide advanced presets",
      wizardBack: "Back",
      wizardNext: "Next",
      wizardStepLabel: "Step",
      wizardSteps: [
        { title: "Input source", description: "Prepare audio, PDF, direct notes, and the project baseline." },
        { title: "Document setup", description: "Choose presets, doc mix, and reusable template sets." },
        { title: "Detail context", description: "Review only the metadata fields that matter for the selected preset." },
      ],
      generationTitle: "Generation setup",
      generationDescription:
        "Docs are generated individually behind the scenes. Here you can use presets or pick only the docs you need.",
      viewGuide: "Open selection guide",
      selectedDocs: (count: number) => `${count} selected docs`,
      startGeneration: "Start generating docs",
      emptyTitle: "No document bundle has been created yet.",
      emptyMessage:
        "Add an audio file, meeting note, or customer complaint, choose the docs you need, and continue through PRD, supporting docs, saved structure, and next actions in one flow.",
      emptyAction: "Open selection guide",
    },
    viewer: {
      uploadDone: "Upload complete",
      audioToText: "Audio to text",
      pdfExtract: "Extract PDF text",
      pdfAnalyze: "Analyze PDF structure",
      dualMerge: "Dual-AI merge",
      workingDocs: "Generate working docs",
      completed: "Completed",
      failedTitle: "Document generation stopped",
      noticeTitle: "Could not load progress",
      docResultsTitle: "Document results",
      docResultsDescription: "Browse the PRD and generated support docs by type, and expand the body only when needed.",
      copyCurrentDoc: "Copy current doc",
      downloadMarkdown: "Download .md",
      mergedPrd: "Merged PRD",
      diffReport: "Diff",
      warningPrefix: "Some docs were not generated:",
      baselinePrefix: "Comparison baseline:",
      collapseBody: "Collapse body.",
      expandBody: "Expand to inspect the full body.",
      sectionCardsTitle: "Section cards",
      sectionCardsDescription: "Review sections as cards and regenerate only the part that needs refinement.",
      regenerateSection: "Regenerate",
      regenerateSectionHint: "Add a hint (optional)",
      regenerateSectionPlaceholder: "Example: Expand customer impact and rollback criteria",
      regenerateSectionSubmit: "Regenerate this section",
      regenerateSectionCancel: "Cancel",
      regenerateUnavailable: "Section regeneration is available only for the merged PRD or saved support docs.",
      savedTreeTitle: "Saved structure",
      savedTreeDescription: "Reopen generated docs and `next-actions` files from the saved PRD bundle as a tree.",
      currentBundle: "Current PRD bundle",
      artifacts: "artifacts/",
      nextActions: "next-actions/",
      noSavedNextActions: "No saved next-action drafts yet.",
      nextActionsTitle: "Next actions",
      nextActionsDescription: "Generate PM / FE / BE / QA / CS / GitHub Issue follow-up drafts from the PRD.",
      quickActionsEyebrow: "Continue fast",
      quickActionsTitle: "Push the result into the next workflow",
      quickActionsDescription: "The most common follow-ups are pinned here. Open PM/FE drafts immediately, then send the PRD to Obsidian or copy an issue draft in one click.",
      quickActionGenerate: "Generate",
      quickActionOpen: "Open",
      quickActionReady: "A draft is already ready.",
      quickActionGenerateHint: "Create a fresh draft from the current PRD.",
      obsidianCardTitle: "Send to Obsidian",
      obsidianCardDescription: "Save the merged PRD directly into the Obsidian vault Inbox or the vault root.",
      obsidianCardCta: "Save to Obsidian",
      obsidianSetupCta: "Set vault path",
      obsidianSetupHint: "Set `paths.obsidianVault` in the runtime settings file to enable export.",
      obsidianTargetLabel: "Target:",
      githubIssueCardTitle: "Copy GitHub issue draft",
      githubIssueCardDescription: "Summarize the PRD into an issue-body format and copy it to the clipboard.",
      githubIssueCardHint: "This copies only. It does not call `gh`.",
      githubIssueCardCta: "Copy issue draft",
      actionDraftCopy: "Copy draft",
      actionDraftDownload: "Download draft",
      collapseDraft: "Collapse draft body.",
      expandDraft: "Expand to inspect the full draft.",
      noActionDraftYet: "Choose a role to generate a next-action draft from the current PRD and support docs.",
      noClaudeResult: "(No Claude result)",
      noCodexResult: "(No Codex result)",
      noDiffResult: "(No diff report)",
      noProjectContextWarning: "legacy bundle / no project context",
    },
    history: {
      currentSession: "Current session",
      savedDocs: "Saved docs",
      searchSaved: "Search saved docs",
      legacy: "legacy",
      hasBaseline: "Has baseline",
      noSearchResult: "No results found.",
      page: (current: number, total: number) => `Page ${current} / ${total}`,
      prev: "Previous",
      next: "Next",
      projectUnset: "No project selected",
    },
    guide: {
      closeAria: "Close guide",
      badge: "Selection guide",
      title: "Decide quickly which docs to generate",
      description: "More documents are not always better. The important part is choosing the set that matches the current stage.",
      tabs: {
        presets: "By preset",
        docs: "By doc",
        scenarios: "Suggested scenarios",
      },
      applyPreset: "Apply this preset",
      chooseWhen: "Choose in these cases",
      skipWhen: "Skip for now when",
      useLabel: "Recommended",
      extraLabel: "Extra",
      flowTitle: "Default flow",
      flowSteps: [
        "1. Choose the preset or documents that match the current stage.",
        "2. Review the PRD and support docs in the result view.",
        "3. Reopen saved docs and `next-actions` from the saved structure.",
        "4. Continue with PM / FE / BE / QA / CS follow-up drafts from next actions.",
      ],
    },
    hooks: {
      submitStarted: "Document generation started. Once it finishes, continue from the saved structure and next actions.",
      submitMissingInput: "Upload an audio file or enter text notes, then try again.",
      projectRequired: "Select a project and wait for project context to be ready before trying again.",
      projectContextNotReady: "Project context is not ready yet. Please try again shortly.",
      submitFailed: "Could not start document generation. Check the input and local runtime, then try again.",
      nextActionSaved: (title: string) => `Saved the ${title} draft under next-actions in the bundle.`,
      nextActionCreated: (title: string) => `Generated the ${title} draft.`,
      nextActionFailed: "Failed to generate the next-action draft. Please try again shortly.",
      obsidianExported: (filePath: string | null) => filePath ? `Saved the Obsidian note: ${filePath}` : "Saved the Obsidian note.",
      obsidianExportFailed: "Failed to export to Obsidian. Check the vault path and write permissions.",
      githubIssueCopied: "Copied the GitHub issue draft to the clipboard.",
      githubIssueCopyFailed: "Failed to copy the GitHub issue draft. Please try again.",
      saveTemplateTitle: "Save template set",
      saveTemplateMessage: "Save the current doc mix and generation mode as a reusable template set.",
      saveTemplatePlaceholder: "Enter a template set name.",
      saveTemplateInitial: (projectName?: string) => (projectName ? `${projectName} default set` : "My template"),
      saveLabel: "Save",
      templateSaved: "Saved the current doc setup as a template set.",
      templateDeleted: "Deleted the template set.",
      deleteTemplateTitle: "Delete template set",
      deleteTemplateMessage: "Delete this template set?",
      deleteSavedBundleTitle: "Delete saved bundle",
      deleteSavedBundleMessage: "Delete the saved document bundle together with its next-actions?",
      savedBundleDeleted: "Deleted the saved documents.",
      deleteHistoryTitle: "Delete session record",
      deleteHistoryMessage: "Delete this current session record?",
      historyDeleted: "Deleted the current session record.",
      retryTextRestored: "Restored the input text. Review it and start document generation again.",
      retrySettingsRestored: "Restored the settings. Reattach the original audio/PDF files before retrying.",
      deleteFailed: "Something went wrong while deleting. Please try again shortly.",
      sectionRegenerated: (title: string) => `Regenerated the ${title} section.`,
      sectionRegenerateFailed: "Failed to regenerate the section. Please try again shortly.",
    },
  },
} as const;

