import type { AppLocale } from "@/lib/locale";
import type { MeetingHubMeetingType } from "@/lib/types";

export interface MeetingHubTemplateDefinition {
  type: MeetingHubMeetingType;
  label: string;
  description: string;
  defaultTitle: string;
  notes: string;
}

export function getMeetingHubTemplateDefinitions(locale: AppLocale): MeetingHubTemplateDefinition[] {
  return locale === "ko" ? KOREAN_TEMPLATES : ENGLISH_TEMPLATES;
}

const KOREAN_TEMPLATES: MeetingHubTemplateDefinition[] = [
  {
    type: "standup",
    label: "스탠드업",
    description: "어제 한 일, 오늘 할 일, 블로커를 빠르게 정리합니다.",
    defaultTitle: "데일리 스탠드업",
    notes: [
      "Summary:",
      "- 오늘 공유해야 할 핵심 한 줄",
      "",
      "Discussion:",
      "- 어제 완료한 작업",
      "- 오늘 진행할 작업",
      "",
      "Action:",
      "- @owner 작업 내용 due 2026-03-29",
      "",
      "Risk:",
      "- 블로커 또는 의존성",
      "",
      "Follow-up:",
      "- 내일 확인할 항목",
    ].join("\n"),
  },
  {
    type: "planning",
    label: "플래닝",
    description: "우선순위, 범위, 담당자, 마감일을 정리합니다.",
    defaultTitle: "스프린트 플래닝",
    notes: [
      "Summary:",
      "- 이번 플래닝의 목표",
      "",
      "Decision:",
      "- 이번 주 우선순위",
      "",
      "Action:",
      "- @owner 작업 내용 due 2026-03-29",
      "- @owner 작업 내용 due 2026-03-31",
      "",
      "Risk:",
      "- 일정/리소스 리스크",
      "",
      "Follow-up:",
      "- 다음 검토 시점",
    ].join("\n"),
  },
  {
    type: "review",
    label: "리뷰",
    description: "결과물 검토와 승인/수정 포인트를 남깁니다.",
    defaultTitle: "작업 리뷰",
    notes: [
      "Summary:",
      "- 리뷰 대상과 핵심 결과",
      "",
      "Discussion:",
      "- 잘된 점",
      "- 보완이 필요한 점",
      "",
      "Decision:",
      "- 승인 또는 수정 방향",
      "",
      "Action:",
      "- @owner 수정 내용 due 2026-03-29",
    ].join("\n"),
  },
  {
    type: "retro",
    label: "회고",
    description: "좋았던 점, 아쉬웠던 점, 개선 액션을 남깁니다.",
    defaultTitle: "스프린트 회고",
    notes: [
      "Summary:",
      "- 이번 회고의 핵심 한 줄",
      "",
      "Discussion:",
      "- 잘한 점",
      "- 아쉬운 점",
      "",
      "Decision:",
      "- 다음 사이클에서 유지/중단할 것",
      "",
      "Action:",
      "- @owner 개선 액션 due 2026-03-29",
      "",
      "Follow-up:",
      "- 다음 회고 전에 확인할 항목",
    ].join("\n"),
  },
  {
    type: "client",
    label: "고객 미팅",
    description: "요구사항, 결정, 후속 액션을 고객 기준으로 정리합니다.",
    defaultTitle: "고객 미팅",
    notes: [
      "Summary:",
      "- 고객 요청 또는 핵심 상황",
      "",
      "Discussion:",
      "- 고객이 기대하는 결과",
      "- 제약 사항 / 일정",
      "",
      "Decision:",
      "- 합의된 방향",
      "",
      "Action:",
      "- @owner 고객 후속 답변 due 2026-03-29",
      "- @owner 내부 후속 작업 due 2026-03-31",
      "",
      "Risk:",
      "- 커뮤니케이션 또는 일정 리스크",
    ].join("\n"),
  },
];

const ENGLISH_TEMPLATES: MeetingHubTemplateDefinition[] = [
  {
    type: "standup",
    label: "Standup",
    description: "Capture yesterday, today, and blockers quickly.",
    defaultTitle: "Daily Standup",
    notes: [
      "Summary:",
      "- One-line standup headline",
      "",
      "Discussion:",
      "- What was completed yesterday",
      "- What is planned for today",
      "",
      "Action:",
      "- @owner task description due 2026-03-29",
      "",
      "Risk:",
      "- Blocker or dependency",
      "",
      "Follow-up:",
      "- What to re-check tomorrow",
    ].join("\n"),
  },
  {
    type: "planning",
    label: "Planning",
    description: "Define priorities, scope, owners, and deadlines.",
    defaultTitle: "Sprint Planning",
    notes: [
      "Summary:",
      "- Goal for this planning session",
      "",
      "Decision:",
      "- Weekly priority or scope call",
      "",
      "Action:",
      "- @owner task description due 2026-03-29",
      "- @owner task description due 2026-03-31",
      "",
      "Risk:",
      "- Timeline or staffing risk",
      "",
      "Follow-up:",
      "- Next review checkpoint",
    ].join("\n"),
  },
  {
    type: "review",
    label: "Review",
    description: "Capture approvals, feedback, and follow-up edits.",
    defaultTitle: "Work Review",
    notes: [
      "Summary:",
      "- What was reviewed and the result",
      "",
      "Discussion:",
      "- What worked well",
      "- What needs revision",
      "",
      "Decision:",
      "- Approval or change direction",
      "",
      "Action:",
      "- @owner revision task due 2026-03-29",
    ].join("\n"),
  },
  {
    type: "retro",
    label: "Retro",
    description: "Capture wins, misses, and improvement actions.",
    defaultTitle: "Sprint Retro",
    notes: [
      "Summary:",
      "- One-line retro headline",
      "",
      "Discussion:",
      "- What went well",
      "- What hurt momentum",
      "",
      "Decision:",
      "- What to keep or stop next cycle",
      "",
      "Action:",
      "- @owner improvement task due 2026-03-29",
      "",
      "Follow-up:",
      "- What to validate before the next retro",
    ].join("\n"),
  },
  {
    type: "client",
    label: "Client Meeting",
    description: "Capture requests, decisions, and external follow-up clearly.",
    defaultTitle: "Client Meeting",
    notes: [
      "Summary:",
      "- Main customer request or current situation",
      "",
      "Discussion:",
      "- Expected outcome",
      "- Constraints and timing",
      "",
      "Decision:",
      "- Agreed direction",
      "",
      "Action:",
      "- @owner customer follow-up due 2026-03-29",
      "- @owner internal follow-up due 2026-03-31",
      "",
      "Risk:",
      "- Timeline or communication risk",
    ].join("\n"),
  },
];
